export const aliments = [
  {
    userId: "1",
    img: "Frutas",
    title: "Caixa de Maçãs",
    category: "Fruits",
    validation: "01/02/23",
    description: "Docao de uma remeça de Cereals quase vencisdas",
    amounts: "51",
    address: "São Paulo - SP",
    id: "1",
  },
  {
    userId: "1",
    img: "oils",
    title: "Manteiga",
    category: "oils",
    validation: "01/02/23",
    description: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "Belo Horizonte - MG",
    id: "2",
  },
  {
    userId: "1",
    img: "Vegetables",
    title: "Batatas",
    category: "Vegetables",
    validation: "01/02/23",
    description: "Docao de uma remeça de Vegetables quase vencisdas",
    amounts: "51",
    address: "Vitória - ES",
    id: "3",
  },
  {
    userId: "1",
    img: "CestaBasica",
    title: "Litros de Leite",
    category: "Milk",
    validation: "01/02/23",
    description: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "São Paulo - SP",
    id: "4",
  },
  {
    userId: "1",
    img: "Vegetables",
    title: "Beterraba",
    category: "Vegetables",
    validation: "01/02/23",
    description: "Docao de uma remeça de Vegetables quase vencisdas",
    amounts: "51",
    address: "Rio de Janeiro - RJ",
    id: "5",
  },
  {
    userId: "1",
    img: "CestaBasica",
    title: "Carne Suína",
    category: "MeatAndEggs",
    validation: "01/02/23",
    description: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "São Paulo - SP",
    id: "6",
  },
  {
    userId: "1",
    img: "oils",
    title: "Óleo de Soja",
    category: "oils",
    validation: "01/02/23",
    description: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "Belo Horizonte - MG",
    id: "7",
  },
  {
    userId: "1",
    img: "CestaBasica",
    title: "Carne Bovina",
    category: "MeatAndEggs",
    validation: "01/02/23",
    description: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "Rio de Janeiro - RJ",
    id: "8",
  },
  {
    userId: "1",
    img: "CestaBasica",
    title: "MeatAndEggs",
    category: "Fruits",
    validation: "01/02/23",
    description: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "São Paulo - SP",
    id: "9",
  },
  {
    userId: "1",
    img: "CestaBasica",
    title: "MeatAndEggs",
    category: "Milk",
    validation: "01/02/23",
    description: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "Belo Horizonte - MG",
    id: "10",
  },
];
