export const aliments = [
  {
    userId: 1,
    img: "Frutas",
    title: "Banana",
    category: "oils",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Bananas quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 1,
  },
  {
    userId: 1,
    img: "CestaBasica",
    title: "Cesta Basica",
    category: "oils",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 3,
  },
  {
    userId: 1,
    img: "Frutas",
    title: "Banana",
    category: "Fruits",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Bananas quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 4,
  },
  {
    userId: 1,
    img: "CestaBasica",
    title: "Cesta Basica",
    category: "Fruits",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 5,
  },
];