export const aliments = [
  {
    userId: 1,
    img: "Frutas",
    title: "Cereals",
    category: "Cereals",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Cereals quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 1,
  },
  {
    userId: 1,
    img: "CestaBasica",
    title: "Cesta Basica",
    category: "oils",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 3,
  },
  {
    userId: 1,
    img: "Vegetables",
    title: "Vegetables",
    category: "Vegetables",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Vegetables quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 4,
  },
  {
    userId: 1,
    img: "CestaBasica",
    title: "Cesta Basica",
    category: "Milk",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 5,
  },
  {
    userId: 1,
    img: "Vegetables",
    title: "Vegetables",
    category: "Vegetables",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Vegetables quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 6,
  },
  {
    userId: 1,
    img: "CestaBasica",
    title: "MeatAndEggs Basica",
    category: "MeatAndEggs",
    validation: "01/02/23",
    descripition: "Docao de uma remeça de Maçã quase vencisdas",
    amounts: "51",
    address: "rua x",
    id: 7,
  },
];